#!/usr/bin/env python3
import os
import argparse
try:
    import inttable
except:
    pass
import requests
import subprocess

# Get the INTFRAMEWORK_PATH environment variable
intframework_path = os.getenv("INTFRAMEWORK_PATH")
if not intframework_path:
    print("Error: $INTFRAMEWORK_PATH environment variable is not set.")
    exit(1)

# Change the working directory to INTFRAMEWORK_PATH
try:
    os.chdir(intframework_path)
except FileNotFoundError:
    print(f"Error: The directory {intframework_path} was not found.")
    exit(1)

def fetch_data_from_url(url):
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raises an exception for HTTP errors
        return response.text  # Returns the page content
    except requests.exceptions.RequestException as e:
        print(f"Error: {e}")
        return None

url = "https://raw.githubusercontent.com/intSpLoiT/intframework/refs/heads/%C4%B0ntframeworkV4/version.md"
data = fetch_data_from_url(url)

inttable.core.activate("root")

# Execute commands from a file
def ecff(file_path):
    try:
        with open(file_path, 'r') as file:
            commands = file.readlines()
            for command in commands:
                command = command.strip()
                if command:
                	os.system(f"python3 {intframework_path}/remote.py {command}")
    except FileNotFoundError:
        print("File not found.")
    
    if not file_path.endswith((".int4", ".int")):
        print("Please use a .int4 or .int file.")

# Move this file to the bin directory and set permissions
s = __file__
if "bin" not in s:
    os.chmod(__file__, 0o755)  # Set file permissions
    os.system(f"mv {__file__} $PREFIX/bin")

# Process arguments
parser = argparse.ArgumentParser(description="Console Starter")
parser.add_argument("-x", help="Command to execute with intconsole")
parser.add_argument("-i", "--int", help=".int file to read commands from")
parser.add_argument("-q", help="Start intconsole in quiet mode")
parser.add_argument("-v", "--version", help="Show version information")

args = parser.parse_args()

if args.x:
    os.system(f"python3 {intframework_path}/remote.py {args.x}")

if args.int:
    ecff(args.int)

if args.q:
    os.system(f"python3 {intframework_path}/quited.py")

if args.version and data:
    print(data)  # Print the data

if not any(vars(args).values()):
    try:
        os.system(f"python3 {intframework_path}/intconsoleV4.py")
    except:
        os.system("python3 intconsoleV4.py")
