#!/usr/bin/env python3
from sqlmap import sqlmap
import platform
import sys

def iplatform():
    user = platform.platform().lower()
    if "linux" in user:
        if sys.stdin.isatty():
            us = "intvp2.5.0.1.dev-bb096ce34 console"
        else:
            us = "intvp2.5.0.1.dev-bb096ce34 gui"
    elif "android" in user:
        us = "Android-İntikam21-ConsoleV4.0.1.98"
    elif "macos" in user:
        us = "macos-consoleV4.0.1.98"
    else:
        us = "Unknown platform"
    
    print(us)
# sqlmap modülündeki işlevlerin ve sınıfların listesini
print("intframework")
sqlmap.main()
s = iplatform()
print(f"""author:sqlmap.com developer:sqlmapproject
platform:{s}""")