import os
import importlib.util
import time
import math
from datetime import datetime
import subprocess
import requests  # Requests modülünü dahil ettik

# Modül yükleme fonksiyonu
def load_module(module_name):
    try:
            if module_name.endswith(".py"):
                        spec = importlib.util.spec_from_file_location("module", module_name)
                                    module = importlib.util.module_from_spec(spec)
                                                spec.loader.exec_module(module)
                                                        else:
                                                                    raise ImportError("Sadece .py uzantılı dosyalar yüklenebilir.")
                                                                        except Exception as e:
                                                                                print(f"Modül yüklenirken hata: {e}")

                                                                                # print fonksiyonu (Python'daki print işlevi)
                                                                                def int4_print(message):
                                                                                    try:
                                                                                            print(message)
                                                                                                except Exception as e:
                                                                                                        print(f"Print hatası: {e}")

                                                                                                        # WiFi ağlarını tarama
                                                                                                        def scan_wifi():
                                                                                                            try:
                                                                                                                    print("WiFi ağları taranıyor...")
                                                                                                                            result = subprocess.run(['nmcli', 'dev', 'wifi'], capture_output=True, text=True)
                                                                                                                                    print(result.stdout)
                                                                                                                                        except Exception as e:
                                                                                                                                                print(f"WiFi tarama hatası: {e}")

                                                                                                                                                # WiFi ağına bağlanma
                                                                                                                                                def connect_wifi(ssid, password):
                                                                                                                                                    try:
                                                                                                                                                            print(f"{ssid} ağına bağlanıyor...")
                                                                                                                                                                    subprocess.run(['nmcli', 'dev', 'wifi', 'connect', ssid, 'password', password], check=True)
                                                                                                                                                                            print(f"{ssid} ağına başarıyla bağlanıldı.")
                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                        print(f"Bağlantı hatası: {e}")

                                                                                                                                                                                        # HTTP GET isteği
                                                                                                                                                                                        def http_get(url):
                                                                                                                                                                                            try:
                                                                                                                                                                                                    response = requests.get(url)
                                                                                                                                                                                                            if response.status_code == 200:
                                                                                                                                                                                                                        print(f"GET isteği başarılı! Yanıt: {response.text}")
                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                            print(f"GET isteği başarısız! Hata Kodu: {response.status_code}")
                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                        print(f"GET isteği hatası: {e}")

                                                                                                                                                                                                                                                        # HTTP POST isteği
                                                                                                                                                                                                                                                        def http_post(url, data):
                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                    response = requests.post(url, data=data)
                                                                                                                                                                                                                                                                            if response.status_code == 200:
                                                                                                                                                                                                                                                                                        print(f"POST isteği başarılı! Yanıt: {response.text}")
                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                            print(f"POST isteği başarısız! Hata Kodu: {response.status_code}")
                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                        print(f"POST isteği hatası: {e}")

                                                                                                                                                                                                                                                                                                                        # JSON verisi işleme
                                                                                                                                                                                                                                                                                                                        def handle_json(url):
                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                    response = requests.get(url)
                                                                                                                                                                                                                                                                                                                                            if response.status_code == 200:
                                                                                                                                                                                                                                                                                                                                                        data = response.json()
                                                                                                                                                                                                                                                                                                                                                                    print(f"JSON verisi: {data}")
                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                        print(f"JSON isteği başarısız! Hata Kodu: {response.status_code}")
                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                    print(f"JSON işleme hatası: {e}")

                                                                                                                                                                                                                                                                                                                                                                                                    # Web sayfası çekme
                                                                                                                                                                                                                                                                                                                                                                                                    def fetch_webpage(url):
                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                response = requests.get(url)
                                                                                                                                                                                                                                                                                                                                                                                                                        if response.status_code == 200:
                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Web sayfası içeriği: {response.text[:200]}...")  # İlk 200 karakteri yazdırıyoruz
                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Web sayfası çekme hatası! Hata Kodu: {response.status_code}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Web sayfası hatası: {e}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Fonksiyonlar ve işlemler
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def test(module_name):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                              