name: Intframework

on:
  push:
    branches:
      - İntframeworkV4
  pull_request:
    branches:
      - İntframeworkV4
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        chmod +x terbuild.sh

    - name: Run tests for Intframework
      run: |
        ls -la

    - name: Inttable
      run: |
        cd inttable

  notify:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Notify deployment status
      uses: actions/github-script@v6
      with:
        script: |
          console.log('Deployment status: success')